/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as OptionsIndexRouteImport } from './routes/options/index'
import { Route as OptionsOptionNumberRouteImport } from './routes/options/$optionNumber'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as ScheduleDateRouteImport } from './routes/schedule/$date'
import { Route as ScheduleArchivedScheduleIdRouteImport } from './routes/schedule/archived/$scheduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsIndexRoute = OptionsIndexRouteImport.update({
  id: '/options/',
  path: '/options/',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsOptionNumberRoute = OptionsOptionNumberRouteImport.update({
  id: '/options/$optionNumber',
  path: '/options/$optionNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleDateRoute = ScheduleDateRouteImport.update({
  id: '/schedule/$date',
  path: '/schedule/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleArchivedScheduleIdRoute =
  ScheduleArchivedScheduleIdRouteImport.update({
    id: '/schedule/archived/$scheduleId',
    path: '/schedule/archived/$scheduleId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/options/$optionNumber': typeof OptionsOptionNumberRoute
  '/schedule/$date': typeof ScheduleDateRoute
  '/options/': typeof OptionsIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/schedule/archived/$scheduleId': typeof ScheduleArchivedScheduleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/options/$optionNumber': typeof OptionsOptionNumberRoute
  '/schedule/$date': typeof ScheduleDateRoute
  '/options': typeof OptionsIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/schedule/archived/$scheduleId': typeof ScheduleArchivedScheduleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/options/$optionNumber': typeof OptionsOptionNumberRoute
  '/schedule/$date': typeof ScheduleDateRoute
  '/options/': typeof OptionsIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/schedule/archived/$scheduleId': typeof ScheduleArchivedScheduleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklist'
    | '/options/$optionNumber'
    | '/schedule/$date'
    | '/options/'
    | '/schedule/'
    | '/schedule/archived/$scheduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklist'
    | '/options/$optionNumber'
    | '/schedule/$date'
    | '/options'
    | '/schedule'
    | '/schedule/archived/$scheduleId'
  id:
    | '__root__'
    | '/'
    | '/checklist'
    | '/options/$optionNumber'
    | '/schedule/$date'
    | '/options/'
    | '/schedule/'
    | '/schedule/archived/$scheduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistRoute: typeof ChecklistRoute
  OptionsOptionNumberRoute: typeof OptionsOptionNumberRoute
  ScheduleDateRoute: typeof ScheduleDateRoute
  OptionsIndexRoute: typeof OptionsIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  ScheduleArchivedScheduleIdRoute: typeof ScheduleArchivedScheduleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/': {
      id: '/options/'
      path: '/options'
      fullPath: '/options/'
      preLoaderRoute: typeof OptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/$optionNumber': {
      id: '/options/$optionNumber'
      path: '/options/$optionNumber'
      fullPath: '/options/$optionNumber'
      preLoaderRoute: typeof OptionsOptionNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$date': {
      id: '/schedule/$date'
      path: '/schedule/$date'
      fullPath: '/schedule/$date'
      preLoaderRoute: typeof ScheduleDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/archived/$scheduleId': {
      id: '/schedule/archived/$scheduleId'
      path: '/schedule/archived/$scheduleId'
      fullPath: '/schedule/archived/$scheduleId'
      preLoaderRoute: typeof ScheduleArchivedScheduleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistRoute: ChecklistRoute,
  OptionsOptionNumberRoute: OptionsOptionNumberRoute,
  ScheduleDateRoute: ScheduleDateRoute,
  OptionsIndexRoute: OptionsIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  ScheduleArchivedScheduleIdRoute: ScheduleArchivedScheduleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
