/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OptionsIndexRouteImport } from './routes/options/index'
import { Route as OptionsOptionNumberRouteImport } from './routes/options/$optionNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsIndexRoute = OptionsIndexRouteImport.update({
  id: '/options/',
  path: '/options/',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsOptionNumberRoute = OptionsOptionNumberRouteImport.update({
  id: '/options/$optionNumber',
  path: '/options/$optionNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/options/$optionNumber': typeof OptionsOptionNumberRoute
  '/options/': typeof OptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/options/$optionNumber': typeof OptionsOptionNumberRoute
  '/options': typeof OptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/options/$optionNumber': typeof OptionsOptionNumberRoute
  '/options/': typeof OptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/options/$optionNumber' | '/options/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/options/$optionNumber' | '/options'
  id: '__root__' | '/' | '/options/$optionNumber' | '/options/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OptionsOptionNumberRoute: typeof OptionsOptionNumberRoute
  OptionsIndexRoute: typeof OptionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/': {
      id: '/options/'
      path: '/options'
      fullPath: '/options/'
      preLoaderRoute: typeof OptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/$optionNumber': {
      id: '/options/$optionNumber'
      path: '/options/$optionNumber'
      fullPath: '/options/$optionNumber'
      preLoaderRoute: typeof OptionsOptionNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OptionsOptionNumberRoute: OptionsOptionNumberRoute,
  OptionsIndexRoute: OptionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
